[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/event/*"
  to = "/event/index.html"
  status = 200

[[redirects]]
  from = "/check-in/*"
  to = "/check-in/index.html"
  status = 200
