[build]
  publish = "."

[[redirects]]
  from = "/event/*"
  to = "/event/index.html"
  status = 200

[[redirects]]
  from = "/check-in/*"
  to = "/check-in/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
