async function loadEvent(){const id=new URLSearchParams(location.search).get('id');if(!id)return fail('No event selected.');try{const e=await(await fetch(`/events/${id}/event.json`)).json();render(e)}catch{fail('This event could not be loaded.')}}function render(e){document.title=`${e.title} | LwLAT Events`;document.getElementById('event-title').textContent=e.title;
const hero=document.getElementById('event-hero');
const existingLogo=document.getElementById('event-brand-logo');
if(existingLogo) existingLogo.remove();
if(e.eventLogo){
  const logo=document.createElement('img');
  logo.id='event-brand-logo';
  logo.className='event-brand-logo';
  logo.src=e.eventLogo;
  logo.alt=e.title;
  hero.insertBefore(logo, hero.querySelector('h1'));
}document.getElementById('event-subtitle').textContent=e.subtitle;document.getElementById('event-date').textContent=e.date;document.getElementById('event-time').textContent=e.time;document.getElementById('event-venue').textContent=e.venue;document.getElementById('footer-event-title').textContent=e.title;const status=document.getElementById('event-status');status.textContent=e.status;status.className=`status ${e.statusClass||''}`;const hero=document.getElementById('event-hero');hero.style.backgroundImage=`linear-gradient(rgba(7,27,32,.35),rgba(7,27,32,.72)),url('${e.heroImage}')`;hero.style.backgroundSize='cover';hero.style.backgroundPosition='center';const form=document.getElementById('registration-form');const formName=`lwlat-events-${e.id}`;form.setAttribute('name',formName);document.getElementById('form-name').value=formName;document.getElementById('event-id').value=e.id;document.getElementById('event-name').value=e.title;document.getElementById('lunch-choice').innerHTML='<option value="">Please choose</option>'+e.lunchOptions.map(x=>`<option>${esc(x)}</option>`).join('');document.getElementById('session-1').innerHTML='<option value="">Please choose</option>'+e.session1.map(x=>`<option>${esc(x)}</option>`).join('');document.getElementById('session-2').innerHTML='<option value="">Please choose</option>'+e.session2.map(x=>`<option>${esc(x)}</option>`).join('');document.getElementById('register-button').textContent=`Register for ${e.title}`;if(!e.registrationOpen)document.getElementById('registration-card').innerHTML='<p class="eyebrow">Registration</p><h2>Registration is not currently open.</h2>'}function fail(m){document.getElementById('event-title').textContent=m;document.getElementById('registration-card').style.display='none'}function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}loadEvent();